import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const beaconToken = process.env.NEXT_PUBLIC_CF_BEACON_TOKEN;

  return (
    <html lang="en">
      <head>
        {beaconToken ? (
          <script
            dangerouslySetInnerHTML={{
              __html: `window.CLOUDFLARE_BEACON_TOKEN=${JSON.stringify(
                beaconToken,
              )};`,
            }}
          />
        ) : null}
      </head>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
